class AppText{

  static const appTextList = [
    "Choose Location",
    "Choose your location for near hospitals",
    "Country",
    "Address",
    "Next",
    "Choose Language",
    "Choose language for app to show",
    "French",
    "Primary Language",
    "Arabic",
    "English",
    "Spanish",
    "Expert Doctor",
    "Advice Online",
    "Access top-tier medical expertise from the comfort of your home. Our platform connects you with specialized doctors for personalized advice and care, anytime, anywhere.",
    "Doctor Support, Always",
    "Ready",
    "Our dedicated doctors are here to support you 24/7. Whether it's a simple consultation or urgent advice, you can count on us to be there when you need it most.",
    "Stay Healthy,",
    "Stay Connected",
    "Your health is our priority. Stay connected with your healthcare providers and maintain your well-being through seamless, continuous care and support.",
    "Choose Account Type",
    "Patient",
    "Health Professional",
    "Login",
    "Register",
    "Sign In",
    "Access your account securely. Sign in to manage your personalized experience.",
    "Email",
    "Password",
    "Profile",
    "Enter email",
    "Forgot Password?",
    "Forgot Password",
    "Or Continue With",
    "Don’t have an account?",
    "Sign Up",
    " Sign Up ",
    "here",
    "Create an Account",
    "Sign up today for personalized health insights and exclusive member perks!",
    "Confirm Password",
    "Remember Password",
    "Already have an account?",
    "Reset your password securely for uninterrupted access to your account.",
    "Send OTP",
    "Verify OTP",
    "Verify",
    "Enter OTP code received to authenticate your identity and complete verification",
    "Did’nt receive email?",
    "Resend",
    "Personalized Dashboard",
    "Appointment Management (Limited to 15 Appointment/Month",
    "Access to Medical Resources (Limited Selection)",
    "Basic Notifications & Alerts",
    "Multilingual Support",
    "Free",
    "Basic",
    "Premium",
    "Advance",
    "Get Started",
    "350 dhs/Month",
    "All Features from Free Offer",
    "Smart Agenda",
    "Appointment Confirmation and Reminders",
    "Practice/Clinic Appointment Management",
    "Video Consultation / Home Visits / In-office / At Clinic",
    "Instant Messaging",
    "Access for Assistants",
    "SMS Reminders",
    "Prescription Creation",
    "DocShare",
    "550 dhs/Month",
    "All Features from Basic Offer",
    "Comprehensive Access to Electronic Medical Records (EMR)",
    "Unlimited Electronic Prescriptions",
    "Advanced Patient Management",
    "Detailed Reports & Analytics",
    "Unlimited Document Management",
    "Integration with Medical Devices",
    "Advance Notifications and Alerts",
    "Offline Access",
    "Priority Customer Support",
    "Automated Search",
    "Let’s Find Your Doctor",
    "Upcoming Schedule",
    "Doctor Speciality",
    "Top Doctor",
    "Dr.",
    "Personal Info",
    "Payment",
    "Language",
    "Help Center",
    "Log Out",
    "Are you sure you want to log out",
    "Logout",
    "Cancel",
    "View All",
    "Appointment",
    "Notification",
    "Latest Update",
    "My Favourite Doctor",
    "Make an appointment",
    "No Found",
    "About Doctor",
    "Fees Information",
    "Schedules",
    "Patients details",
    "Full Name",
    "Name",
    "Hi",
    "Female",
    "File should be pdf, docx or pptx",
    "Add a file",
    "or drop it here",
    "Continue",
    "Select Your Age Range",
    "Phone Number",
    "Gender",
    "Male",
    "Write Your Problem",
    "Any Documented Test Reports",
    "You can now make multiple doctoral appointments at once You can  appointments at once You can",
    "Make Payment",
    "Consulting",
    "Other Manipulation",
    "Other Service",
    "Total",
    "Booking Confirmed",
    "Start Appointment",
    "Video Call Ended",
    "Recording have been saved in history",
    "Would you recommend Dr. Marvin to your friends?",
  ];

}